---
- name: Tasks
  hosts: all
  become: yes
  tasks:
    
    - name: Install VSFTPD
      ansible.builtin.dnf:
        state: present
        name: vsftpd
    
    - name: Enable and Start
      ansible.builtin.service:
        name: vsftpd
        enabled: yes
        state: started