---
- name: Tasks
  hosts: all
  become: yes
  tasks:
    - name: Install HTTPD
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Enable and Start HTTPD
      ansible.builtin.service:
        name: httpd
        enabled: yes
        state: started

    - name: Create Index.html
      ansible.builtin.copy:
        dest: "/var/www/html/index.html"
        content: "This is a Nautilus sample file, created using Ansible!"
        owner: apache
        group: apache
        mode: '0644'

    - name: Add to Index.html
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        insertbefore: BOF
        line: 'Welcome to Nautilus Group!'