---
- name: Configure files and symlinks on app servers
  hosts: stapp01,stapp02,stapp03
  become: yes
  tasks:
    - name: Ensure /opt/data directory exists
      ansible.builtin.file:
        path: /opt/data
        state: directory
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0755'

    - name: Create empty file
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: touch
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0644'
      loop:
        - { path: '/opt/data/blog.txt', host: 'stapp01' }
        - { path: '/opt/data/story.txt', host: 'stapp02' }
        - { path: '/opt/data/media.txt', host: 'stapp03' }
      when: inventory_hostname == item.host

    - name: Create symlink to /opt/data
      ansible.builtin.file:
        src: /opt/data
        dest: /var/www/html
        state: link
        force: yes